### ISSUE TITLE
tweepy-authlibの対応について

### ISSUE THREAD

**Issue by my2trr** [tsukumijima/EDCBNotifier#7]
EDCBNotifierを利用させていただいてます。
Twitterにポストできなくなり、今後tweepy-authlibでのポストに対応する予定はございますか。
よろしくお願いいたします。

**Comment by tsukumijima** [comment]
tweepy-authlib はもともと Twitter API v1.1 を継続利用するために開発したものですが、現状 Twitter API v1.1 の statuses/tweet エンドポイントが完全に廃止されてしまったため、ツイート機能を実装するには tweepy-authlib に加えて Twitter Web App の GraphQL API を呼ぶコードを独自に書く必要があります。KonomiTV では実際にそのように実装しています。
ただ、私が EDCBNotifier を LINE Notify や Discord への通知にしか使っておらずモチベーションが高くないこと、非公式な手段のため継続的にメンテナンスが必要となることから、対応予定は当面ありません。ご了承ください。
